# fly.toml app configuration file generated for pandapolls on 2024-05-02T12:24:47+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pandapolls'
primary_region = 'ams'
kill_signal = 'SIGTERM'

[build]

[deploy]
  strategy = "rolling"
  max-per-region = 1

[env]
  PHX_HOST = 'pandapolls.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
